Enaleia/mobile

app/(tabs)/_layout.tsx
app/_layout.tsx
contexts/QueueContext.tsx
utils/batchFetcher.ts

- Added null safety checks for queue items array
- Optimized React Query client configuration for offline-first behavior
- Improved batch data fetching error handling
- Added stale data cleanup functionality
- Updated default query options for better offline support:
- Added `structuralSharing: true` for optimized memory usage
- Disabled `refetchOnMount` 
- Set `refetchOnReconnect: "always"` for reliable data sync
- Removed redundant `retry` and `enabled` options
- Added null check for queueItems array to prevent filter crashes
- Added `clearStaleData` function to remove outdated queries (>24h old)
- Improved error handling in batch fetcher:
- Extracted empty batch data creation to reusable function
- Better handling of FORBIDDEN errors
- Cleaner error collection and reporting
- …

Offline Data Handling & Query Client Optimizations

---

app/(tabs)/index.tsx
app/(tabs)/queue.tsx
app/_layout.tsx
components/features/attest/AddMaterialModal.tsx
components/features/attest/LeaveAttestationModal.tsx
components/features/attest/SentToQueueModal.tsx
components/features/attest/TypeInformationModal.tsx
components/features/auth/SignOutModal.tsx
components/features/initialization/InitializationModal.tsx
components/features/location/LocationPermissionRequest.tsx
components/features/queue/QueueAction.tsx
components/features/queue/QueueSection.tsx
components/features/scanning/QRCodeScanner.tsx
components/features/scanning/QRTextInput.tsx
components/shared/ModalBase.tsx
components/shared/NetworkStatus.tsx
contexts/NetworkContext.tsx
contexts/QueueContext.tsx
package.json
pnpm-lock.yaml
services/backgroundTaskManager.ts
utils/directus.ts

- Added NetworkContext for centralized network state management
- Improved queue retry logic and offline handling
- Enhanced accessibility across components
- Cleaned up network status display
- Created NetworkContext to handle connection state and type
- Moved network status logic from individual components to context
- Added automatic queue retry on network recovery
- Improved queue item cleanup for completed items older than 24h
- Added battery status monitoring for background tasks
- Simplified network status indicator with connection type
- Added comprehensive accessibility labels and hints
- Improved error states and retry flows
- Enhanced modal dialogs with proper ARIA roles
- expo-battery: ~9.0.2
- Multiple component files updated with accessibility improvements
- New …

 Network Status and Queue Management Improvements

---

app/attest/new/[slug].tsx

fixes https://github.com/Enaleia/mobile/issues/32
- save state(on form change) with storage.
- restore state when resume from background
- tested locally

fixes form error on resume from idle

---

app/(tabs)/settings.tsx
app/attest/new/[slug].tsx
components/features/attest/IncompleteAttestationModal.tsx
components/features/attest/LeaveAttestationModal.tsx
components/features/attest/SentToQueueModal.tsx
components/features/auth/SignOutModal.tsx
components/features/location/LocationEducationalModal.tsx
components/features/location/LocationPermissionHandler.tsx

- save skip for now state (WIP)
- modals adjustment, change font size and alignment

modal adjustment

---

app.json
app/(tabs)/queue.tsx
app/(tabs)/settings.tsx
app/_layout.tsx
app/attest/new/[slug].tsx
components/features/queue/QueueSection.tsx
metro.config.js
package-lock.json
package.json
pnpm-lock.yaml

- add sentry
- add empty state in. queue page
- add contact support on setting

add sentry

---

app/attest/new/[slug].tsx
components/features/attest/RequireProductSelectModal.tsx

fixes issue https://github.com/Enaleia/mobile/issues/56
- add field required modal
- show modal on submit when product field missing
- tested locally

show modal if product field missing

---

app/attest/new/[slug].tsx

fixes https://github.com/Enaleia/mobile/issues/56
fix validation to allow null weight on submit form

allow null weight

---

app/attest/new/[slug].tsx
components/features/auth/LoginForm.tsx
contexts/AuthContext.tsx
contexts/WalletContext.tsx
docs/refinements.md
services/queueProcessor.ts
types/enaleia.ts
types/user.ts
types/wallet.ts
utils/directus.ts
utils/eas.ts
utils/storage.ts

- Added wallet address verification and Directus sync
- Implemented dev storage reset functionality
- Fixed EAS weight and coordinate handling
- Cleaned up imports and logging
- [ba55d59](https://github.com/Enaleia/mobile/commit/ba55d592be836d6ff0a6680bcf2b0e2d6c3507b8) - Added dev storage reset button
- [81d161a](https://github.com/Enaleia/mobile/commit/81d161a49efb315474a7af90f3501b8ca7849021) - Added wallet verification and sync
- [ed1b14f](https://github.com/Enaleia/mobile/commit/ed1b14f2011d99e3a2313d0acd0420d497518826) - Fixed EAS weight/coordinate handling
- Wallet ownership verification against stored private key
- Automatic wallet recreation if verification fails
- Wallet address syncing with Directus user profile
- Dev-only storage reset button in login screen
- …

Wallet Management and Storage Improvements

---

app/(tabs)/index.tsx
app/(tabs)/queue.tsx
services/queueProcessor.ts

- Fix Collector name 
- Post EAS UID after successfully attested to directus
- Remove clearing cache from home screen and queue
Fixes #67 
Fixes #69

fixes #67 & #69

---

services/queueProcessor.ts
utils/eas.ts

fixes https://github.com/Enaleia/mobile/issues/67
- Create reusable collectors function for use in both directus and eas requests
-  Map collectorName
- Concat id to  inComingCode when using collectorId as input_code

fix maps to eas body

---

utils/eas.ts

remove falsy item when concat arrays(remove comma)

remove falsy item

---

app/attest/new/[slug].tsx
services/queueProcessor.ts
utils/eas.ts

fixes #80, #79 & #81
-  fix company 
-  fix array code
- add Outgoing material should include the QR field in collection actions

fixes company & array code &  out-code

---

services/eas.ts
types/enaleia.ts
utils/eas.ts

update new schema so weight per item can take decimal

update to new schema

---

services/queueProcessor.ts

fixes #80
- fix save company to directus
- move fetchRequirdData() out from loop

fixes company

---

app/attest/new/[slug].tsx
services/queueProcessor.ts
utils/eas.ts

fix incoming code length doesn't match cause unable to post on EAS

---

utils/eas.ts

- remove filter
- now array will match the length, when there is no data, in uint16, we will write 0, string we will write null (empty)

fix array alignment

---

app/(tabs)/queue.tsx
app/queue/[id].tsx
components/features/attest/MaterialSection.tsx
components/features/queue/QueueAction.tsx
components/features/scanning/QRTextInput.tsx

Queue details
queue ui refinements
ect

Queue details page ++

---

app/(tabs)/queue.tsx
components/features/queue/QueueAction.tsx
components/features/queue/QueueSection.tsx
services/queueProcessor.ts

only 2 queue sections
- active : pending
:failed
:processing
:offline
:slow_retry
- complete

combine sections

---

app/queue/[id].tsx
app/settings/queue-test.tsx
components/features/auth/LoginForm.tsx
components/features/location/LocationEducationalModal.tsx
components/features/location/LocationPermissionRequest.tsx
components/features/queue/ProcessingSpinner.tsx
components/features/queue/QueueAction.tsx
components/features/queue/QueueSection.tsx
components/features/queue/QueueStatusIndicator.tsx
components/features/queue/ServiceStatusIndicator.tsx
components/features/scanning/QRTextInput.tsx
components/features/settings/TestFormSubmission.tsx
components/shared/DecimalInput.tsx
components/shared/FieldInfo.tsx
components/shared/SelectField.tsx

Update/queue UI

---

components/features/location/LocationPermissionRequest.tsx
components/features/queue/QueueSection.tsx
components/features/queue/QueueStatusIndicator.tsx

- spinner
- warning msg during processing
- syntax fix in location permission request

add spinner in queue status

---

app/queue/[id].tsx
components/features/queue/QueueSection.tsx
services/queueDebugMonitor.ts
services/queueProcessor.ts
types/queue.ts

- Moved slow retry logic from directus status to queue item level
- Removed retry all btn from queue page, retry from queue detail page

Moved slow retry logic

---

app/(tabs)/queue.tsx
app/queue/[id].tsx
app/settings/queue-test.tsx
components/features/queue/QueueSection.tsx
contexts/QueueContext.tsx

- disable refresh status on in completely failed items

Fix/double sending UI

---

app/(tabs)/settings.tsx
app/queue/[id].tsx
components/features/queue/QueueSection.tsx
contexts/QueueContext.tsx
services/queueProcessor.ts

Revert "total retry counter fix, minor ui, add test:0.1 in builder number"
